// generated by unplugin-svelte-components
// We suggest you to commit this file into source control
declare global {
    const CommonHeader: typeof import("./components/common/Header.svelte")["default"]
    const CommonText: typeof import("./components/common/Text.svelte")["default"]
}

export {}
